### ISSUE TITLE
Units affected by multiple Prismatic Shield instances should have them displayed separately instead of on a single buff.

### ISSUE THREAD

**Issue by fcalife** [fcalife/dota_tactics#11]
Title.

* Since this actually requires a small rework on the ability's mechanics, I'd like to request to ignore this issue, unless it is deemed important enough (i.e. if you guys think that having a counter instead of multiple buff icons is confusing for players, or the like).

**Comment by bradus** [comment]
ignore this issue

**Comment by fcalife** [comment]
Done
